version: '3.8'

services:
  web:
    build: ./php
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: uthhealth_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: uth_health
      MYSQL_USER: uth_user
      MYSQL_PASSWORD: uth_pass
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
